Change <brainfuck.h> to "brainfuck.h"
When a compiler sees <> tags, it searches for the included file (this is for linux users) in /usr/include. Brainfuck.h is not in that directory, so it has to have "" tags, or it gives this error
fatal error: brainfuck.h: No such file or directory